// Derives the site's ABIs from the Foundry build of the pinned source commit
// (run `forge build --skip test --skip script` at the repository root first) and
// writes them to src/lib/abi/generated.ts. It also compares a few canonical
// keccak forms of each ABI with the abiHash values in .imd/reads/deployment.json
// when that file is present, and prints which form (if any) matches.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { keccak256, stringToHex } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");
const outDir = join(root, "out");
const names = ["PLEA", "CabalGate", "PleaHook", "PleaDistributor", "PleaLaunch"];

function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((k) => [k, sortKeys(value[k])]));
  }
  return value;
}

const abis = {};
for (const name of names) {
  const file = join(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`missing ${file}; run forge build first`);
  abis[name] = JSON.parse(readFileSync(file, "utf8")).abi;
}

const deploymentFile = join(root, ".imd", "reads", "deployment.json");
if (existsSync(deploymentFile)) {
  const deployment = JSON.parse(readFileSync(deploymentFile, "utf8"));
  for (const c of deployment.contracts) {
    const abi = abis[c.name];
    if (!abi) continue;
    const forms = {
      "json(sorted keys, compact)": JSON.stringify(sortKeys(abi)),
      "json(forge order, compact)": JSON.stringify(abi),
      "json(sorted entries by type+name, sorted keys)": JSON.stringify(
        sortKeys([...abi].sort((a, b) => `${a.type}:${a.name ?? ""}`.localeCompare(`${b.type}:${b.name ?? ""}`)))
      ),
    };
    const matches = Object.entries(forms)
      .map(([label, text]) => [label, keccak256(stringToHex(text)).slice(2)])
      .filter(([, h]) => h === c.abiHash)
      .map(([label]) => label);
    console.log(`${c.name}: abiHash ${c.abiHash.slice(0, 12)}… ${matches.length ? `matches ${matches.join(", ")}` : "no tried canonical form matched"}`);
  }
}

const header = `// Generated by scripts/gen-abi.mjs from the Foundry build of the pinned source commit.\n// Do not edit by hand; run \`npm run abi\` after \`forge build\`.\n`;
let body = header;
for (const name of names) {
  const varName = (name === name.toUpperCase() ? name.toLowerCase() : name.charAt(0).toLowerCase() + name.slice(1)) + "Abi";
  body += `\nexport const ${varName} = ${JSON.stringify(abis[name])} as const;\n`;
}
const target = join(here, "..", "src", "lib", "abi");
mkdirSync(target, { recursive: true });
writeFileSync(join(target, "generated.ts"), body);
console.log(`wrote ${join(target, "generated.ts")}`);
